language: java
jdk: openjdk-13

addons:
  sonarcloud:
    organization: "inseefr"
    token:
      secure: "UR/ho2DmIiyeBGHKFGsyRhiUIt4YG3cKQcJWAXLViMxIHKKLjwwr3qt3rAyUSG3JI1y1I1WCrrGy8SPqIwv1SRg9NB42504mOlMGj/0Db0gJ10O/hhM5i8ZVHD4Y4e1fj8CcaPvj2LA+bPKy1m7iX4dHG++vEwjwVt4beSLfuqYML5lHHVtX7INX7efjnMpB0AG9dz0mRWwyj2iScl76ZaQ/GnJxsyuGVwcy0Dm/SwlZxqWp7KoTJeqyGq5467tC917h98adG3UsHWENODqwrRNy8yoMRtxWRIELGUilU5ceAIQDxPUJi7mPMtJTvmqJUs/5ZG45UuPStab9vdsKJMpWMI3C88NG/OQA1I4lWqvCsK+sDWzrsd+o3QbxFOvqdBh6e/Qd3CLTcCjHrL4odcFDfmuDwYfWN2ZAP0bVoPs3nPTrSwfcN61ze3FP09cZAjdZclL8nyf62sNeVHhRbQNnlcYREXuhQmdwNnHUK5oga4iK2IYo1gg97qaqFB/2WqRCAGRJfWteZ4YK2oBR53gvSVYZMpzOU6wtcxiHPsMIDi41txr3F0Gf0fAJxneDJlQfZknDGx5x4LOHh4xPIcaJhIzAMn6CXFs6B+jJP871rEpYPa3+0fGYvq0ZG0ZUS4OAOh4jppbcmzl3zQc2ReAjslFECFMboDJhaC2UYsA="

script:
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=InseeFr_Trevas

after_script:
  - bash scripts/gitbook.sh
