language: java
jdk: openjdk13

git:
  depth: false

addons:
  sonarcloud:
    organization: "inseefr"

script:
  - mvn clean verify sonar:sonar -Dsonar.projectKey=InseeFr_Trevas

after_script:
  - bash scripts/gitbook.sh
