language: java
jdk: openjdk-13

git:
  depth: false

addons:
  sonarcloud:
    organization: "inseefr"
    token:
      secure: "aGUOwsX/WJhBp5a873o28OQxFJkbP9ZrayBs0g4XUi+tuU/6p1wqdhO1Wo4z9LYJ+pGqgNzECfwPU025Ty6ahdqQAIRAbahJw9jKqnTpFSGznBn9SbXltneK5Ur05IZHX+kukPQ1o2Ar+vNJzy4IE7TXrSjEau8o58Rb9gWGvM0s72JQVZWTWGubznO3NRSCAp108T7SNs8Jjr+c4cjy+pMfLX939+4XofwhbUyMYTWgmkT25caDR2U7U88pAdBzoICR8iD7Va8jWfp/Be7MCENwmeN/awM88pIjfAWb+geSwPx/FrmbIuIKtMzNdqxsettghv93A3Zmf7bAUbUNB2sJeypL/IFDK8UFyoGTNKEpTiM3zKmZFeP0/RrSBWdReqC4tWCB7DXXaNc0EJ4wvq5cR+uLjcN3NEAkD8d1zUjl7hrxCR7BQhGHUj+uNgJLOKSRQ8e7ie+dVgrB/IG+CJs4h8Zsh/cQ9KBfmX0lJkGrE/G1CP7CG/zQ4dEDKV0z2axMIKTNQ3zs/4ycjHJ/mgfXYNtY8i2qO4gpIA70YFuJwKo6d7TafMv/4OuHPIfjGDrzFEL1TdQLc6XoFXEsPu7RQHh98RaIBLWNPoZ/H4xcERgkaaxKYHPSB+gXJU4iuZuFp5laCnLe2ijL+sZJHazcXXOoTd6B/FDoXswJgnQ="

script:
  - mvn clean verify sonar:sonar -Dsonar.projectKey=InseeFr_Trevas

after_script:
  - bash scripts/gitbook.sh