language: java
jdk: openjdk-13

addons:
  sonarcloud:
    organization: "inseefr"

addons:
  sonarcloud:
    organization: "inseefr"

script:
  - mvn clean verify sonar:sonar

after_script:
  - bash scripts/gitbook.sh
