/** This module exposes the constructs generated by Antlr from the VTL grammar files. */
module fr.insee.vtl.parser {
  requires transitive fr.insee.vtl.antlr;

  exports fr.insee.vtl.parser;

  opens fr.insee.vtl.parser;
}
