/** This module exposes the constructs generated by Antlr from the VTL grammar files. */
module fr.insee.vtl.parser {
  requires org.antlr.antlr4.runtime;

  exports fr.insee.vtl.parser;

  opens fr.insee.vtl.parser;
}
