name: Trevas CI

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - "!master"
      - "!develop"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11.0.4
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Test
        run: mvn test
