name: Trevas CI

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    if: github.repository != 'inseefr/trevas'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "adopt"
      - name: Test
        run: mvn test
  package:
    if: github.repository != 'inseefr/trevas'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "adopt"
      - name: Test
        run: mvn package
  test-sonar-package:
    if: github.repository == 'inseefr/trevas'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "adopt"
      - name: Test, package and analyze with maven & SonarCloud
        run: mvn verify sonar:sonar -Pcoverage -Dsonar.projectKey=InseeFr_Trevas -Dsonar.organization=inseefr -Dsonar.host.url=https://sonarcloud.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
