name: Trevas CI

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Run Trevas tests
    # Fork or Trevas main repo branch with PR coming from fork
    if: github.repository != 'InseeFr/Trevas' ||
        github.event.pull_request.head.repo.fork == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "adopt"
      - name: Test
        run: mvn test
  package:
    name: Package Trevas modules
    # Fork or Trevas main repo branch with PR coming from fork
    if: github.repository != 'InseeFr/Trevas' ||
        github.event.pull_request.head.repo.fork == 'true'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "adopt"
      - name: Test
        run: mvn package
  test-sonar-package:
    name: Run Trevas tests with coverage & sonar checks
    # Trevas main repo commit branch or merged PR
    if: github.repository == 'InseeFr/Trevas' ||
        github.event.pull_request.head.repo.fork == 'false' ||
        (github.event.pull_request.head.repo.fork == 'true' &&
        github.event.pull_request.merged == 'true')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "adopt"
      - name: Test, package and analyze with maven & SonarCloud
        run: mvn verify sonar:sonar -Pcoverage -Dsonar.projectKey=InseeFr_Trevas -Dsonar.organization=inseefr -Dsonar.host.url=https://sonarcloud.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  publish-release:
    name: Publish Trevas modules on Maven
    if: (github.repository == 'InseeFr/Trevas' ||
        github.event.pull_request.merged == 'true') &&
        startsWith(github.event.ref, 'refs/tags/v')
    needs: test-sonar-package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Publish Trevas
        run: mvn -B -Prelease deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
  publish-snapshot:
    name: Publish Trevas modules SNAPSHOT on Github Packages
    if: (github.repository == 'InseeFr/Trevas' ||
        github.event.pull_request.merged == 'true') && 
        github.ref == 'refs/heads/develop'
    needs: package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "adopt"
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_OPTS: -Dorg.slf4j.simpleLogger.defaultLogLevel='warn'
