name: Trevas docs publication
on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@v1
        with:
          source-folder: docs
          git-user: github-action
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages
