name: Trevas docs publication
on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.19.0
      - name: Gitbook Action
        uses: ZanderZhao/gitbook-action@master
        with:
          source_dir: docs
          token: ${{ secrets.GITHUB_TOKEN }}
