name: Publish Trevas packages to GitHub Packages
on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11.0.4
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_OPTS: -Dorg.slf4j.simpleLogger.defaultLogLevel=${{ inputs.logLevel || 'warn'}}
