name: Publish Trevas packages to GitHub Packages
on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "adopt"
      - uses: s4u/maven-settings-action@v3.0.0
        with:
          githubServer: false
          servers: |
            [{
                "id": "Github",
                "username": "${{ secrets.GH_PACKAGES_USERNAME }}",
                "password": "${{ secrets.GH_PACKAGES_PASSWORD }}"
            }]
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_OPTS: -Dorg.slf4j.simpleLogger.defaultLogLevel=${{ inputs.logLevel || 'warn'}}
