name: Run VTL TF TCK

on:
  push:
    branches: ['**']
  pull_request:
    branches: [master, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main project
        uses: actions/checkout@v4

      - name: Clone vtl spec repo (branch fix/tck-2.1)
        run: git clone --branch fix/tck-2.1 https://github.com/sdmx-twg/vtl.git

      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run TCK generator script
        run: |
          DOC_VERSION=v2.1 python3 vtl/scripts/generate_tck_files.py

      - name: Move generated TCK zip to resources
        run: |
          mkdir -p coverage/src/main/resources
          mv vtl/tck/v2.1.zip coverage/src/main/resources/

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and run tests
        run: mvn clean test --batch-mode

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports

      - name: Publish JUnit test results
        if: always()
        uses: dorny/test-reporter@v2
        with:
          name: JUnit Test Report
          path: target/surefire-reports/*.xml
          reporter: java-junit
